name: Test and Deploy App
on:
  push:
    branches: main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get The Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying
        run: echo "Deployed..."
